server:
  port: 8081

spring:
  application:
    name: greeting-client

grpc:
  client:
    greeting-grpc-client:
      address: greeting-service
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
