server:
  port: 8081

spring:
  application:
    name: greeting-client

eureka:
  instance:
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
  client:
    fetch-registry: true

grpc:
  client:
    greeting-grpc-client:
#      address: "static://localhost:9090"
      address: "discovery:///greeting-service"
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext

