server:
  port: 8082


spring:
  application:
    name: greeting-service

eureka:
  instance:
    metadata-map:
      grpc-port: 9082
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

grpc:
  server:
    port: 9082
